<div id="left" class="account">
<h2><?php echo $this->pageTitle('Account registration'); ?></h2>
<h3>Please fill out this form to begin the registration procedure:</h3>
<ol>
<li>Upon succesful completion of this form we will ask you to activate your account by clicking a
link we will send to you in an email, this lets us verify that you are receiving emails from us
correctly.</li>
<?php if($this->group): ?>
<li>Once your account has been activated the <?php $this->escape($this->group->title); ?> leader will
be asked to accept you into the <?php echo $this->groupAbbr($this->group); ?> group.</li>
<li>If you are accepted, you'll then be able to use the <?php echo $this->groupAbbr($this->group);
?> forum and message <?php echo $this->groupAbbr($this->group); ?> members.</li>
<?php else: ?>
<li>Once your account has been activated the leader of your chosen group will
be asked to accept you into their group.</li>
<li>If you are accepted, you'll then be able to use the group forum and message group members.</li>
<?php endif; ?>
</ol>
<h3>Terms and Conditions</h3>
<p>By registering here you agree to be bound by the
<a href="<?php
 echo $this->url(array('controller' => 'legal', 'action' => 'terms'), 'default');
 ?>">Terms and Conditions of Use of This Website</a></p>
</div>
<div id="right" class="account">
<h2>Registration form</h2>
<p>Fields marked with * are mandatory and must be filled in.</p>
<?php echo $this->form; ?>
</div>