<div id="left" class="account">
<h2>Changing your details</h2>
<p>Use this form to change your details.</p>
<h3>Please note</h3>
<ol>
<li>Changing your first or last names will change your full name as displayed on the site, 
this is the name other users use to find you.</li>
<li>If you change you email address, an activation email will be sent to the new address. 
Once you have completed the activation procedure for the new address you'll be able to use it with the site,
until such time, you'll still need to use your old email address for logging in.</li>
</ol>
</div>

<div id="right" class="account">
<h2><?php echo $this->pageTitle('My Details'); ?></h2>
<?php echo $this->messages(); ?>
<p>Fields marked with * are mandatory and must be filled in.</p>
<?php echo $this->form; ?>
</div>