<div id="left" class="account">
<h2>About forum settings</h2>
<p>Forum setting allow you to control how you appear within the forum.</p>
<ol>
<li>Your picture appears next to your name on forum posts and messages.</li>
<li>Your post signature appears at the bottom of your forum posts and messages.</li>
</ol>
</div>
<div id="right" class="account">
<h2><?php echo $this->pageTitle('Forum Settings'); ?></h2>
<?php echo $this->messages(); ?>
<p>Compete this form to change your forum settings:</p>
<?php echo $this->form; ?>
</div>