<div id="left" class="account">
<h2>Changing your password</h2>
<p>Use this form to change your password.</p>
<h3>Please be careful</h3>
<ol>
<li>Changing your password to something you won't remember can mean you won't be able to log in.</li>
<li>Should you find you can't log in, you can use the password reset request form to reset your password via email.</li>
</ol>
</div>
<div id="right" class="account">
<h2><?php echo $this->pageTitle('Change Password'); ?></h2>
<?php echo $this->messages(); ?>
<p>Fields marked with * are mandatory and must be filled in.</p>
<?php echo $this->form; ?>
</div>