<?php

/**
 * Model_Base_Group
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $has_gallery
 * @property string $title
 * @property string $description
 * @property string $abbr
 * @property string $teaser
 * @property string $intro
 * @property Doctrine_Collection $Event
 * @property Doctrine_Collection $CaseStudy
 * @property Doctrine_Collection $Gallery
 * @property Doctrine_Collection $User
 * @property Doctrine_Collection $UserGroup
 * @property Doctrine_Collection $Topic
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Group extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('group');
        $this->hasColumn('has_gallery', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('title', 'string', 63, array(
             'type' => 'string',
             'notblank' => true,
             'length' => '63',
             ));
        $this->hasColumn('description', 'string', 127, array(
             'type' => 'string',
             'length' => '127',
             ));
        $this->hasColumn('abbr', 'string', 8, array(
             'type' => 'string',
             'length' => '8',
             ));
        $this->hasColumn('teaser', 'string', 127, array(
             'type' => 'string',
             'length' => '127',
             ));
        $this->hasColumn('intro', 'string', 102400, array(
             'type' => 'string',
             'length' => '102400',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_User as User', array(
             'refClass' => 'Model_UserGroup',
             'local' => 'group_id',
             'foreign' => 'user_id'));

        $this->hasMany('Model_UserGroup as UserGroup', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('Model_Topic as Topic', array(
             'local' => 'id',
             'foreign' => 'group_id'));
    }
}