<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_Group', 'doctrine');

/**
 * Model_Base_Group
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property string $abbr
 * @property Doctrine_Collection $UserGroup
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Group extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('group');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 63, array(
             'type' => 'string',
             'length' => 63,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('description', 'string', 127, array(
             'type' => 'string',
             'length' => 127,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('abbr', 'string', 8, array(
             'type' => 'string',
             'length' => 8,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_UserGroup as UserGroup', array(
             'local' => 'id',
             'foreign' => 'group_id'));
    }
}