<?php

/**
 * Model_Base_MessageImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $message_id
 * @property string $image
 * @property Model_Message $Message
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_MessageImage extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('message_image');
        $this->hasColumn('message_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('image', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Message as Message', array(
             'local' => 'message_id',
             'foreign' => 'id'));
    }
}