<?php

/**
 * Model_Base_Message
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $type
 * @property integer $from_user_id
 * @property string $subject
 * @property string $body
 * @property Doctrine_Collection $To
 * @property Model_User $From
 * @property Doctrine_Collection $UserMessage
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Message extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('message');
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'message',
              1 => 'request',
              2 => 'report',
             ),
             ));
        $this->hasColumn('from_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('subject', 'string', 63, array(
             'type' => 'string',
             'notblank' => true,
             'length' => '63',
             ));
        $this->hasColumn('body', 'string', 102400, array(
             'type' => 'string',
             'length' => '102400',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_User as To', array(
             'refClass' => 'Model_UserMessage',
             'local' => 'message_id',
             'foreign' => 'user_id'));

        $this->hasOne('Model_User as From', array(
             'local' => 'from_user_id',
             'foreign' => 'id'));

        $this->hasMany('Model_UserMessage as UserMessage', array(
             'local' => 'id',
             'foreign' => 'message_id'));
    }
}