<?php

/**
 * Model_Base_PostImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $post_id
 * @property string $image
 * @property Model_Post $Post
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_PostImage extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('post_image');
        $this->hasColumn('post_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('image', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Post as Post', array(
             'local' => 'post_id',
             'foreign' => 'id'));
    }
}