<?php

/**
 * Model_Base_Project
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $created_user_id
 * @property timestamp $created_date
 * @property string $title
 * @property Model_User $Creator
 * @property Doctrine_Collection $Milestone
 * @property Doctrine_Collection $List
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Project extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('project');
        $this->hasColumn('created_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('created_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('title', 'string', 127, array(
             'type' => 'string',
             'length' => '127',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_User as Creator', array(
             'local' => 'created_user_id',
             'foreign' => 'id'));

        $this->hasMany('Model_Milestone as Milestone', array(
             'local' => 'id',
             'foreign' => 'project_id'));

        $this->hasMany('Model_List as List', array(
             'local' => 'id',
             'foreign' => 'project_id'));
    }
}