<?php

/**
 * Model_Base_Todo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $list_id
 * @property integer $created_user_id
 * @property timestamp $created_date
 * @property integer $completed_user_id
 * @property timestamp $completed_date
 * @property integer $weight
 * @property string $title
 * @property string $notes
 * @property Model_User $Creator
 * @property Model_User $Completor
 * @property Model_List $List
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Todo extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('todo');
        $this->hasColumn('list_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('created_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('created_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('completed_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('completed_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('weight', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('title', 'string', 127, array(
             'type' => 'string',
             'length' => '127',
             ));
        $this->hasColumn('notes', 'string', 1023, array(
             'type' => 'string',
             'length' => '1023',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_User as Creator', array(
             'local' => 'created_user_id',
             'foreign' => 'id'));

        $this->hasOne('Model_User as Completor', array(
             'local' => 'completed_user_id',
             'foreign' => 'id'));

        $this->hasOne('Model_List as List', array(
             'local' => 'list_id',
             'foreign' => 'id'));
    }
}