<?php

/**
 * Model_Base_UserMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $message_id
 * @property enum $status
 * @property Model_User $User
 * @property Model_Message $Message
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_UserMessage extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user_message');
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('message_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'new',
              1 => 'read',
              2 => 'deleted',
             ),
             'default' => 'new',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Model_Message as Message', array(
             'local' => 'message_id',
             'foreign' => 'id'));
    }
}