<?php

/**
 * Model_Base_User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $email
 * @property string $password
 * @property timestamp $last_login_date
 * @property Doctrine_Collection $Project
 * @property Doctrine_Collection $Milestone
 * @property Doctrine_Collection $List
 * @property Doctrine_Collection $Todo
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_User extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('email', 'string', 127, array(
             'type' => 'string',
             'length' => '127',
             ));
        $this->hasColumn('password', 'string', 40, array(
             'type' => 'string',
             'length' => '40',
             ));
        $this->hasColumn('last_login_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_Project as Project', array(
             'local' => 'id',
             'foreign' => 'created_user_id'));

        $this->hasMany('Model_Milestone as Milestone', array(
             'local' => 'id',
             'foreign' => 'created_user_id'));

        $this->hasMany('Model_List as List', array(
             'local' => 'id',
             'foreign' => 'created_user_id'));

        $this->hasMany('Model_Todo as Todo', array(
             'local' => 'id',
             'foreign' => 'created_user_id'));
    }
}