<ul id="footer_nav" title="footer navigation">
    <?php foreach($this->nav as $item):
        if($item->isActive()){
            $item->setClass($item->class ? $item->class . ' active' : 'active');
        }
    ?>
    <li<?php if($item->class): ?> class="<?php echo $item->class; ?>"<?php endif; 
    ?>><a title="<?php echo $this->escape($item->title); 
    ?>" href="<?php echo urldecode($item->getHref()); ?>"><?php echo $this->escape($item->label); ?></a></li>
    <?php endforeach; ?>
</ul>