<div class="block-home">
    <h1><?php echo Zend_Registry::get('config')->app->name ?> admin and publishing platform</h1>
    <p>Welcome to the <?php echo Zend_Registry::get('config')->app->name ?> admin and publishing platform. As an online interface, you will be able to publish new content, edit existing entries and upload images, videos or documents to the site.
</p>
<p>Use the left-hand menu to navigate around the publishing platform. By selecting each of the titles you can make changes to the corresponding front-end web page.</p>
                <p>From a content management perspective everything from page titles and body text, to meta information and the number of news entries displayed can be adjusted.</p>
                <p>The tab menu below the main publishing platform banner controls site user accounts, and site-wide reusable 'blocks'.</p>
</div>