<?php

/**
 * Model_MessageImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_MessageImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_MessageImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_MessageImage');
    }
}