<?php

/**
 * Model_MilestoneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_MilestoneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_MilestoneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Milestone');
    }
}