<?php

/**
 * Model_PostImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_PostImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_PostImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_PostImage');
    }
}