<?php

/**
 * Model_UserMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_UserMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_UserMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_UserMessage');
    }
}