<?php echo $this->partial('index/_left.phtml', array('group' => $this->group)); ?>
<div id="right" class="topic">
<?php echo $this->messages(); ?>
<?php if($this->post->isFirst()): ?>
<h2><?php echo $this->pageTitle('Editing topic "' . $this->topic->title . '"'); ?></h2>
<p>Fields marked with * are mandatory and must be filled in.</p>
<?php else: ?>
<h2><?php echo $this->pageTitle('Editing post to topic "' . $this->topic->title . '"'); ?></h2>
<?php endif; if($this->preview):?>
<div id="post_preview">
<table id="posts"><tbody>
<?php echo $this->partial('index/_viewPost.phtml', array('post' => $this->post, 'group' => $this->group)); ?>
</tbody></table>
</div>
<?php endif; ?>
<?php echo $this->form; ?>
</div>