<?php echo $this->partial('index/_left.phtml', array('group' => $this->group)); ?>
<div id="right" class="topic">
<?php echo $this->messages(); ?>
<?php if($this->preview): ?>
<h2><?php echo $this->pageTitle('New topic "' . $this->post->Topic->title . '"'); ?></h2>
<div id="post_preview">
<table id="posts"><tbody>
<?php echo $this->partial('index/_viewPost.phtml', array('post' => $this->post, 'group' => $this->group)); ?>
</tbody></table>
</div>
<?php else: ?>
<h2><?php echo $this->pageTitle('New topic'); ?></h2>
<?php endif; ?>
<p>Fields marked with * are mandatory and must be filled in.</p>
<?php echo $this->form; ?>
</div>