<?php $this->placeholder('subject')->set('Password Reset Request'); ?>
<p>Dear <?php echo $this->to->first_name; ?>,</p>
        
<p>Someone has requested a password reset link for your account.<br/>
If this was you and you wish to reset your password click on the link below,
otherwise simply ignore this email.
</p>

<a href="<?php echo $url = $this->absoluteUrl(array(
	'action' => 'reset', 
	'code' => $this->to->reset_code
), 'account'); ?>"><?php echo $url; ?></a>

<p>Best regards,<br/>
Tidy Mind</p>