<?php

/**
 * Model_GroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_GroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_GroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Group');
    }
}