<?php

/**
 * Model_GroupTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_GroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_GroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Group');
    }

    public function findByAbbr($abbr)
    {
        return $this->createQuery('g')
            ->where('g.abbr = ?', $abbr)
            ->fetchOne();
    }
    
    public function findWithGallery()
    {
        return $this->createQuery('g')
            ->where('g.has_gallery = 1')
            ->execute();
    }

}