<?php

/**
 * Model_ListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_ListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_ListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_List');
    }
}