<?php

/**
 * Model_MessageUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_MessageUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_MessageUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_MessageUser');
    }
}