<?php

/**
 * Model_PostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_PostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_PostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Post');
    }
    
    protected function _getTopicPostsQuery(Model_Topic $topic, Model_Group $group, Model_User $user = null)
    {
        $config = Zend_Registry::get('config');
        $adapter = Zend_Db::factory($config->doctrine->dsn->adapter, $config->doctrine->dsn);

        $permsFields = array(
            '*', 
            'locked' => $topic->status != 'open' ? '(true)' : 
                "(p.status = 'locked' OR (p.posted_date IS NOT NULL AND pl.last IS NULL))"
        );
        $postFields = array('*');
        $selectFields = '{p.*}, {p.last}, {p.locked}, {u.*}, {u.role}';
        
        if($user instanceof Model_User){ 
            $permsFields['user_owns'] = '(p.user_id = ' . $user->id . ')';
            $postFields['user_may_edit'] = 
                $user->isLeaderOfGroup($group) ? '(TRUE)' : '(user_owns AND NOT locked)';
            $selectFields .= ', {p.user_may_edit}, {p.user_owns}';
        }
        
        $lastSelect = $adapter->select()
            ->from('post', array('last' => 'id'))
            ->where('topic_id = ?', $topic->id)
            ->where('posted_date IS NOT NULL')
            ->where("status != 'deleted'")
            ->order('posted_date DESC')
            ->limit(1);
        
        $permsSelect = $adapter->select()
            ->from(array('p' => 'post'), $permsFields)
            ->joinLeft(array('pl' => $lastSelect), 'p.id = pl.last');
        
        $postSelect = $adapter->select()
            ->from(array('p' => $permsSelect), $postFields);

        $userSelect = $adapter->select()
            ->from(array('u' => 'user'))
            ->join(array('ug' => 'user_group'), 'u.id = ug.user_id AND ug.group_id = ' . $group->id, array('role'));
            
        $select = $adapter->select()
            ->from(array('p' => $postSelect), array())
            ->join(array('u' => $userSelect), 'p.user_id = u.id', array());

        $from = $select->assemble();
        $from = substr($from, 5);

        $query = new Doctrine_RawSql();
        $query->addComponent('p', 'Model_Post p')
            ->addComponent('u', 'p.User')
            ->select($selectFields)
            ->from($from)
            ->where('p.topic_id = ?', $topic->id)
            ->andWhere("p.status != 'deleted'");
            
        //die($query->getSqlQuery());
            
        return $query;
    }
    
    public function getTopicPostsQuery(Model_Topic $topic, Model_Group $group, Model_User $user)
    {
        /*
        return $this->createQuery('p')
            ->select('p.*, u.*, ug.role')
            ->innerJoin('p.User u')
            ->innerJoin('u.UserGroup ug WITH ug.group_id = ?', $group->id)
            ->where('p.topic_id = ?', $topic->id)
            ->andWhere('p.status != ?', 'deleted');
        */
        
        $query = $this->_getTopicPostsQuery($topic, $group, $user)
            ->andWhere('p.posted_date IS NOT NULL');
            
        //die($query->getSqlQuery());

        return $query;
    }
    
    public function findDraft($id, Model_user $user, Model_Group $group, Model_Topic $topic)
    {
        /*
        return $this->createQuery('m')
            ->where('m.id = ?', (int)$id)
            ->andWhere('m.user_id = ?', $user->id)
            ->andWhere('m.Topic.group_id = ?', $group->id)
            ->andWhere('m.posted_date IS NULL')
            ->fetchOne();
        */
        
        $q = $this->_getTopicPostsQuery($topic, $group, $user)
            ->andWhere('p.id = ?', $id)
            ->andWhere('(p.user_may_edit OR p.user_owns)')
            ->limit(1);
            
        //die($q->getSqlQuery());
        return $q->execute()->getFirst();
    }
    
    public function findFirstByTopic(Model_Topic $topic)
    {
        return $this->createQuery('m')
            ->where('m.topic_id = ?', $topic->id)
            ->orderBy('created_date')
            ->fetchOne();
    }
    
    public function findRecent($count, Model_Group $group)
    {
        return $this->createQuery('p')
            ->leftJoin('p.Topic t')
            ->where('t.group_id = ?', $group->id)
            ->andWhere('p.posted_date IS NOT NULL')
            ->andWhere("status != 'deleted'")
            ->orderBy('p.posted_date DESC')
            ->limit($count)
            ->execute();
    }
}