<?php

/**
 * Model_TodoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_TodoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_TodoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Todo');
    }
}