<?php

/**
 * Model_TopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_TopicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_TopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Topic');
    }
    
    /*
     Topic:
        columns:
            group_id:
                type: integer
                notnull: true
            user_id:
                type: integer
                notnull: true
            created_date: timestamp
            status:
                type: enum
                values: [open, locked, deleted]
                default: open
                notnull: true
            sticky: 
                type: boolean
                default: false
                notnull: true
            title: 
                type: string(63)
                notblank: true
     */
    
    public function getForumQuery(Model_Group $group)
    {
        // Doctrine seems of less value as time goes on
        $config = Zend_Registry::get('config');
        $adapter = Zend_Db::factory($config->doctrine->dsn->adapter, $config->doctrine->dsn);
        
        $topicStats = $adapter->select()
            ->from('post', array('topic_id', 'id' => 'MAX(id)', 'num_posts' => 'COUNT(id)'))
            ->where("status != 'deleted'")
            ->where('posted_date IS NOT NULL')
            ->group('topic_id');
        
        $select = $adapter->select()
            ->from(array('t' => 'topic'))
            ->join(
                array('u' => 'user'), 
                't.user_id = u.id', 
                array('first_full_name' => "CONCAT(u.first_name, ' ', u.last_name)")
            )    
            ->join(array('ts' => $topicStats), 't.id = ts.topic_id', array('num_posts'))
            ->join(array('lp' => 'post'), 'ts.id = lp.id', array('last_date' => 'created_date'))
            ->join(
                array('lpu' => 'user'),
                'lp.user_id = lpu.id',
                array('last_full_name' => "CONCAT(lpu.first_name, ' ', lpu.last_name)")
            )
            ->where('t.group_id = ?', $group->id)
            ->where("t.status != 'deleted'");

        $from = $select->assemble();
        
        $query = new Doctrine_RawSql();
        $query->addComponent('t', 'Model_Topic t')
            ->select('{t.*}, {t.num_posts}, {t.first_full_name}, {t.last_full_name}, {t.last_date}')
            ->from('(' . $from . ') t');
            
       return $query;
            
    }
    
    public function findOneByIdAndGroup($id, Model_Group $group)
    {
        return $this->createQuery('t')
            ->where('t.id = ?', $id)
            ->andWhere('t.group_id = ?', $group->id)
            ->andWhere('t.status != ?', 'deleted')
            ->fetchOne();
    }
}