<?php

/**
 * Model_UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_User');
    }

    /**
     * Update a user's last login date
     */
    public function updateLastLogin($userId)
    {
	    $user = $this->findOneById($userId);
	    $date = new Zend_Date();
	    $user->last_login_date = $date->get(Zend_Date::ISO_8601);
	    $user->save();
    }
}