<?php

/**
 * Model_UserGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_UserGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_UserGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_UserGroup');
    }
}