<?php $this->pageTitle($this->group->title)->pageTitle('Case Studies'); ?>
<div id="left" class="group <?php echo $this->group->abbr; ?>">

    <h2 class="intro">
        <?php echo $this->escape($this->group->title); ?>
        (<?php echo $this->groupAbbr($this->group); ?>)
    </h2>
    <div>
        <h3>Welcome to the <?php echo $this->escape($this->group->description); ?> case studies page.</h3>
        <p>Each year, we provide direct, practical assistance to those who serve and those who used to serve. 
        Each year we help more than 50,000 different people. Here are some of their stories.</p>
    </div>

    <div id="events">
        <h2><?php echo $this->groupAbbr($this->group); ?> Stories</h2>
        <?php if($this->caseStudies->count() < 1): ?>
            No case studies found.
            <?php else: ?>
            <dl>
            <?php foreach($this->caseStudies as $case): ?>
                <dt><a href="<?php echo $this->url(array('action' => 'case-studies', 'abbr' => $this->group->abbr, 'id' => $case->id), 'groupDetail'); 
                ?>"><?php echo $this->escape($case->title); ?></a></dt>
                <dd>
                    <?php echo $this->escape($case->teaser); ?>
                    <a href="<?php echo $this->url(array('action' => 'case-studies', 'abbr' => $this->group->abbr, 'id' => $case->id), 'groupDetail'); 
                ?>">. . . read more</a>
                </dd>
            <?php endforeach; ?>
            </dl>
            <?php endif; ?>
    </div>

</div>
<div id="right" class="group">

        <?php if(!$this->caseStudy): ?>
            Case study not found.
        <?php else: ?>
        
        <?php $this->pageTitle($this->caseStudy->title); ?>
        
        <?php if($this->caseStudy->image): ?>
        <h2 class="hero"><?php echo $this->escape($this->caseStudy->title); ?></h2>
        <img class="hero" src="<?php echo $this->baseUrl('uploads/images/hero_' . $this->caseStudy->image);
        ?>" alt="<?php echo $this->escape($this->caseStudy->title); ?>"/>
        <?php endif; ?>

        <div id="body-text">
            <h3><?php echo $this->escape($this->caseStudy->title); ?></h3>
            <?php echo $this->caseStudy->body; ?>
        </div>
        
        <?php endif;?>

</div>