<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('list', 'list_created_user_id_user_id', array(
             'name' => 'list_created_user_id_user_id',
             'local' => 'created_user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('list', 'list_project_id_project_id', array(
             'name' => 'list_project_id_project_id',
             'local' => 'project_id',
             'foreign' => 'id',
             'foreignTable' => 'project',
             ));
        $this->createForeignKey('list', 'list_milestone_id_milestone_id', array(
             'name' => 'list_milestone_id_milestone_id',
             'local' => 'milestone_id',
             'foreign' => 'id',
             'foreignTable' => 'milestone',
             ));
        $this->createForeignKey('milestone', 'milestone_created_user_id_user_id', array(
             'name' => 'milestone_created_user_id_user_id',
             'local' => 'created_user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('milestone', 'milestone_completed_user_id_user_id', array(
             'name' => 'milestone_completed_user_id_user_id',
             'local' => 'completed_user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('milestone', 'milestone_project_id_project_id', array(
             'name' => 'milestone_project_id_project_id',
             'local' => 'project_id',
             'foreign' => 'id',
             'foreignTable' => 'project',
             ));
        $this->createForeignKey('project', 'project_created_user_id_user_id', array(
             'name' => 'project_created_user_id_user_id',
             'local' => 'created_user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('todo', 'todo_created_user_id_user_id', array(
             'name' => 'todo_created_user_id_user_id',
             'local' => 'created_user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('todo', 'todo_completed_user_id_user_id', array(
             'name' => 'todo_completed_user_id_user_id',
             'local' => 'completed_user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('todo', 'todo_list_id_list_id', array(
             'name' => 'todo_list_id_list_id',
             'local' => 'list_id',
             'foreign' => 'id',
             'foreignTable' => 'list',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('list', 'list_created_user_id_user_id');
        $this->dropForeignKey('list', 'list_project_id_project_id');
        $this->dropForeignKey('list', 'list_milestone_id_milestone_id');
        $this->dropForeignKey('milestone', 'milestone_created_user_id_user_id');
        $this->dropForeignKey('milestone', 'milestone_completed_user_id_user_id');
        $this->dropForeignKey('milestone', 'milestone_project_id_project_id');
        $this->dropForeignKey('project', 'project_created_user_id_user_id');
        $this->dropForeignKey('todo', 'todo_created_user_id_user_id');
        $this->dropForeignKey('todo', 'todo_completed_user_id_user_id');
        $this->dropForeignKey('todo', 'todo_list_id_list_id');
    }
}