<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adduser extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => 127,
             ),
             'password' => 
             array(
              'type' => 'string',
              'length' => 40,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('user');
    }
}