<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('list');
        $this->dropTable('milestone');
        $this->dropTable('project');
        $this->dropTable('todo');
        $this->createTable('group', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notblank' => '1',
              'length' => '63',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '127',
             ),
             'abbr' => 
             array(
              'type' => 'string',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('user_group', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'group_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'role' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'request',
              1 => 'member',
              2 => 'leader',
              ),
              'default' => 'request',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addColumn('user', 'registration_date', 'timestamp', '25', array(
             ));
        $this->addColumn('user', 'registration_code', 'string', '40', array(
             ));
        $this->addColumn('user', 'member_no', 'string', '63', array(
             ));
        $this->addColumn('user', 'avatar', 'string', '32', array(
             ));
        $this->addColumn('user', 'signature', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->createTable('list', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'project_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'milestone_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '127',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->createTable('milestone', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'project_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'due_date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'completed_user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'completed_date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '127',
             ),
             'notes' => 
             array(
              'type' => 'string',
              'length' => '1023',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->createTable('project', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'created_user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '127',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->createTable('todo', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'list_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'completed_user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'completed_date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'weight' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'default' => '0',
              'length' => '8',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '127',
             ),
             'notes' => 
             array(
              'type' => 'string',
              'length' => '1023',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->dropTable('group');
        $this->dropTable('user_group');
        $this->removeColumn('user', 'registration_date');
        $this->removeColumn('user', 'registration_code');
        $this->removeColumn('user', 'member_no');
        $this->removeColumn('user', 'avatar');
        $this->removeColumn('user', 'signature');
    }
}