<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('message', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'message',
              1 => 'request',
              2 => 'report',
              ),
              'length' => '',
             ),
             'from_user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'subject' => 
             array(
              'type' => 'string',
              'notblank' => '1',
              'length' => '63',
             ),
             'body' => 
             array(
              'type' => 'string',
              'length' => '102400',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('user', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => '127',
             ),
             'password' => 
             array(
              'type' => 'string',
              'length' => '40',
             ),
             'registration_date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'activation_date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'activation_code' => 
             array(
              'type' => 'string',
              'length' => '40',
             ),
             'last_login_date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'last_login_attempt_date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'num_login_attempts' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'reset_request_date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'reset_code' => 
             array(
              'type' => 'string',
              'length' => '40',
             ),
             'first_name' => 
             array(
              'type' => 'string',
              'length' => '63',
             ),
             'last_name' => 
             array(
              'type' => 'string',
              'length' => '63',
             ),
             'member_no' => 
             array(
              'type' => 'string',
              'length' => '63',
             ),
             'avatar' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'signature' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('user_group', array(
             'user_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'group_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'role' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'request',
              1 => 'member',
              2 => 'leader',
              ),
              'default' => 'request',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'user_id',
              1 => 'group_id',
             ),
             ));
        $this->createTable('user_message', array(
             'user_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'message_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'status' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'new',
              1 => 'read',
              2 => 'deleted',
              ),
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'user_id',
              1 => 'message_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('message');
        $this->dropTable('user');
        $this->dropTable('user_group');
        $this->dropTable('user_message');
    }
}