<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('message', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'message',
              1 => 'request',
              2 => 'report',
              ),
              'length' => '',
             ),
             'from_user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notblank' => '1',
              'length' => '63',
             ),
             'body' => 
             array(
              'type' => 'string',
              'length' => '102400',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('message_user', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'message_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'status' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'new',
              1 => 'read',
              2 => 'deleted',
              ),
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('message');
        $this->dropTable('message_user');
    }
}