<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('user', 'last_login_attempt_date', 'timestamp', '25', array(
             ));
        $this->addColumn('user', 'num_login_attempts', 'integer', '8', array(
             ));
        $this->addColumn('user', 'reset_request_date', 'timestamp', '25', array(
             ));
        $this->addColumn('user', 'reset_code', 'string', '40', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('user', 'last_login_attempt_date');
        $this->removeColumn('user', 'num_login_attempts');
        $this->removeColumn('user', 'reset_request_date');
        $this->removeColumn('user', 'reset_code');
    }
}