<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addtopic extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('topic', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'group_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'created_date' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'status' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'open',
              1 => 'locked',
              2 => 'deleted',
              ),
              'default' => 'open',
              'notnull' => true,
              'length' => NULL,
             ),
             'sticky' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'notnull' => true,
              'length' => 25,
             ),
             'title' => 
             array(
              'type' => 'string',
              'notblank' => true,
              'length' => 63,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('topic');
    }
}