<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addgroup extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('group', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'has_gallery' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'default' => 0,
              'length' => 25,
             ),
             'title' => 
             array(
              'type' => 'string',
              'notblank' => true,
              'length' => 63,
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => 127,
             ),
             'abbr' => 
             array(
              'type' => 'string',
              'length' => 8,
             ),
             'teaser' => 
             array(
              'type' => 'string',
              'length' => 127,
             ),
             'intro' => 
             array(
              'type' => 'string',
              'length' => 102400,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('group');
    }
}