<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addtodo extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('todo', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'list_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'created_user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'created_date' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'completed_user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'completed_date' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'weight' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'default' => 0,
              'length' => 8,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 127,
             ),
             'notes' => 
             array(
              'type' => 'string',
              'length' => 1023,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('todo');
    }
}