<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpost extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('post', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'topic_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'created_date' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'posted_date' => 
             array(
              'type' => 'timstamp',
              'length' => NULL,
             ),
             'last_edit_date' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'status' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'open',
              1 => 'locked',
              2 => 'deleted',
              ),
              'default' => 'open',
              'notnull' => true,
              'length' => NULL,
             ),
             'body' => 
             array(
              'type' => 'string',
              'length' => 102400,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('post');
    }
}