<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpostimage extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('post_image', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'post_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'image' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('post_image');
    }
}