<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('list', 'list_created_user_id_user_id', array(
             'name' => 'list_created_user_id_user_id',
             'local' => 'created_user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('list', 'list_project_id_project_id', array(
             'name' => 'list_project_id_project_id',
             'local' => 'project_id',
             'foreign' => 'id',
             'foreignTable' => 'project',
             ));
        $this->createForeignKey('list', 'list_milestone_id_milestone_id', array(
             'name' => 'list_milestone_id_milestone_id',
             'local' => 'milestone_id',
             'foreign' => 'id',
             'foreignTable' => 'milestone',
             ));
        $this->createForeignKey('message', 'message_from_user_id_user_id', array(
             'name' => 'message_from_user_id_user_id',
             'local' => 'from_user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('message_image', 'message_image_message_id_message_id', array(
             'name' => 'message_image_message_id_message_id',
             'local' => 'message_id',
             'foreign' => 'id',
             'foreignTable' => 'message',
             ));
        $this->createForeignKey('milestone', 'milestone_created_user_id_user_id', array(
             'name' => 'milestone_created_user_id_user_id',
             'local' => 'created_user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('milestone', 'milestone_completed_user_id_user_id', array(
             'name' => 'milestone_completed_user_id_user_id',
             'local' => 'completed_user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('milestone', 'milestone_project_id_project_id', array(
             'name' => 'milestone_project_id_project_id',
             'local' => 'project_id',
             'foreign' => 'id',
             'foreignTable' => 'project',
             ));
        $this->createForeignKey('post', 'post_topic_id_topic_id', array(
             'name' => 'post_topic_id_topic_id',
             'local' => 'topic_id',
             'foreign' => 'id',
             'foreignTable' => 'topic',
             ));
        $this->createForeignKey('post', 'post_user_id_user_id', array(
             'name' => 'post_user_id_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('post_image', 'post_image_post_id_post_id', array(
             'name' => 'post_image_post_id_post_id',
             'local' => 'post_id',
             'foreign' => 'id',
             'foreignTable' => 'post',
             ));
        $this->createForeignKey('project', 'project_created_user_id_user_id', array(
             'name' => 'project_created_user_id_user_id',
             'local' => 'created_user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('todo', 'todo_created_user_id_user_id', array(
             'name' => 'todo_created_user_id_user_id',
             'local' => 'created_user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('todo', 'todo_completed_user_id_user_id', array(
             'name' => 'todo_completed_user_id_user_id',
             'local' => 'completed_user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('todo', 'todo_list_id_list_id', array(
             'name' => 'todo_list_id_list_id',
             'local' => 'list_id',
             'foreign' => 'id',
             'foreignTable' => 'list',
             ));
        $this->createForeignKey('topic', 'topic_group_id_group_id', array(
             'name' => 'topic_group_id_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'group',
             ));
        $this->createForeignKey('topic', 'topic_user_id_user_id', array(
             'name' => 'topic_user_id_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('user_group', 'user_group_user_id_user_id', array(
             'name' => 'user_group_user_id_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('user_group', 'user_group_group_id_group_id', array(
             'name' => 'user_group_group_id_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'group',
             ));
        $this->createForeignKey('user_message', 'user_message_user_id_user_id', array(
             'name' => 'user_message_user_id_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('user_message', 'user_message_message_id_message_id', array(
             'name' => 'user_message_message_id_message_id',
             'local' => 'message_id',
             'foreign' => 'id',
             'foreignTable' => 'message',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('list', 'list_created_user_id_user_id');
        $this->dropForeignKey('list', 'list_project_id_project_id');
        $this->dropForeignKey('list', 'list_milestone_id_milestone_id');
        $this->dropForeignKey('message', 'message_from_user_id_user_id');
        $this->dropForeignKey('message_image', 'message_image_message_id_message_id');
        $this->dropForeignKey('milestone', 'milestone_created_user_id_user_id');
        $this->dropForeignKey('milestone', 'milestone_completed_user_id_user_id');
        $this->dropForeignKey('milestone', 'milestone_project_id_project_id');
        $this->dropForeignKey('post', 'post_topic_id_topic_id');
        $this->dropForeignKey('post', 'post_user_id_user_id');
        $this->dropForeignKey('post_image', 'post_image_post_id_post_id');
        $this->dropForeignKey('project', 'project_created_user_id_user_id');
        $this->dropForeignKey('todo', 'todo_created_user_id_user_id');
        $this->dropForeignKey('todo', 'todo_completed_user_id_user_id');
        $this->dropForeignKey('todo', 'todo_list_id_list_id');
        $this->dropForeignKey('topic', 'topic_group_id_group_id');
        $this->dropForeignKey('topic', 'topic_user_id_user_id');
        $this->dropForeignKey('user_group', 'user_group_user_id_user_id');
        $this->dropForeignKey('user_group', 'user_group_group_id_group_id');
        $this->dropForeignKey('user_message', 'user_message_user_id_user_id');
        $this->dropForeignKey('user_message', 'user_message_message_id_message_id');
    }
}